name: shaktiscan0
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  mobile_scanner: ^7.0.1       # Camera and quick scan functionality
  wifi_scan: ^0.4.1+2          # WiFi and network scanning
  geolocator: ^14.0.2          # Location services for SOS mode
  url_launcher: ^6.2.2
  shared_preferences: ^2.1.1   # Open SMS, email, or dialer for SOS alerts

  camera: ^0.10.5+5            # For live camera preview
  tflite_flutter: ^0.11.0      # TensorFlow Lite inference
  image: ^4.1.3                # Image processing for model input
  permission_handler: ^11.0.1  # Runtime permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/model_unquant.tflite
    - assets/labels.txt
